/**
 *
 * @file      vpp/logo.hpp
 *
 * @brief     This is the VPP overlay logo description file
 *
 * @details   This file has been autogenerated from img/vpp.png.
 *            This is a 128 x 90 sRGB image using 8-bit channels.
 *
 *            This file is part of the VPP framework (see link).
 *
 * @author    img2c (autogenerated file)
 *
 * @copyright (c) 2019-2020 Olivier Stoltz-Douchet
 * @license   http://opensource.org/licenses/MIT MIT
 * @link      https://github.com/ezdayo/vpp
 *
 **/

#pragma once

#include <cstdint>

namespace VPP {
namespace Logo {

/** Width of the image in pixels */
extern const int width;

/** Height of the image in pixels */
extern const int height;

/** 8-bit BGR data of the image (3 channels per pixels) */
extern const uint8_t *bgr;

/** 8-bit alpha data of the image */
extern const uint8_t *alpha;

}  // namespace Logo
}  // namespace VPP

